import { StyleSheet} from 'react-native'
export const globalstyle = StyleSheet.create({
    container:{
        flex: 1, 
        backgroundColor: '#DDDFE3', 
        paddingHorizontal: 20,
        justifyContent:'center'
    },
    TextInput:{
        flex:1,
    height:50,
    borderRadius:6,
    borderWidth:1,
    borderColor:'gray',
    flexDirection:'row',paddingLeft:10,alignItems:'center',marginRight:20
    },
    //marginTop
    mt5:{
        marginTop:5
    },
    mt10:{
        marginTop:10
    },
    mt15:{
        marginTop:15
    },
    mt20:{
        marginTop:20
    },
    mt25:{
        marginTop:25
    },
    mt30:{
        marginTop:30
    },
    //marginBottom
    mb5:{
        marginBottom:5
    },
    mb10:{
        marginBottom:10
    },
    mb15:{
        marginBottom:15
    },
    mb20:{
        marginBottom:20
    },
    mb25:{
        marginBottom:25
    },
    mb30:{
        marginBottom:30
    },
    //paddingTop
    pt5:{
        paddingTop:5
    },
    pt10:{
        paddingTop:10
    },
    pt15:{
        paddingTop:15
    },
    pt20:{
        paddingTop:20
    },
    pt25:{
        paddingTop:25
    },
    pt30:{
        marginTop:30
    },
    //paddingBottom
    pb5:{
        paddingBottom:5
    },
    pb10:{
        paddingBottom:10
    },
    pb15:{
        paddingBottom:15
    },
    pb20:{
        paddingBottom:20
    },
    pb25:{
        paddingBottom:25
    },
    pb30:{
        paddingBottom:30
    },
}); 